const products = [
  {
    productId: "P001",
    productName: "Amul Milk 1L",
    category: "Dairy",
    description: "Fresh toned milk",
    price: 60,
    unit: "1L",
    brand: "Amul",
    stock: 100,
    image: "https://shop.amul.com/s/62fa94df8c13af2e242eba16/664b30fb556780e2403991be/01-hero-image_calci-plus-milk-1-l_12-packs-360x360.png",
    rating: 4.5,
    reviews: 120,
    discount: 5
  },
  {
    productId: "P002",
    productName: "Paneer 200g",
    category: "Dairy",
    description: "Fresh soft paneer",
    price: 90,
    unit: "200g",
    brand: "Mother Dairy",
    stock: 50,
    image: "https://m.media-amazon.com/images/I/71kip8jehUL._SL1500_.jpg",
    rating: 4.4,
    reviews: 80,
    discount: 10
  },
  {
    productId: "P003",
    productName: "Banana",
    category: "Fruits",
    description: "Fresh bananas",
    price: 40,
    unit: "1 dozen",
    brand: "Local Farm",
    stock: 150,
    image: "https://www.instacart.com/image-server/296x296/d2lnr5mha7bycj.cloudfront.net/product-image/file/primary_0c8ac7c0-ae07-4d49-91d9-a08075d85269.jpg",
    rating: 4.2,
    reviews: 60,
    discount: 0
  },
  {
    productId: "P004",
    productName: "Apple",
    category: "Fruits",
    description: "Red delicious apples",
    price: 180,
    unit: "1kg",
    brand: "Kashmir Fresh",
    stock: 80,
    image: "https://sp.yimg.com/ib/th?id=OPHS.ImkIbxp%2bMmKnog474C474&o=5&pid=21.1",
    rating: 4.6,
    reviews: 200,
    discount: 15
  },
  {
    productId: "P005",
    productName: "Potato",
    category: "Vegetables",
    description: "Fresh potatoes",
    price: 25,
    unit: "1kg",
    brand: "Local",
    stock: 200,
    image: "https://s.alicdn.com/@sc04/kf/A6b8fca325ada4ff7a34b641a88b492cf9.jpg_100x100.jpg",
    rating: 4.1,
    reviews: 50,
    discount: 0
  },
  {
    productId: "P006",
    productName: "Tomato",
    category: "Vegetables",
    description: "Fresh tomatoes",
    price: 30,
    unit: "1kg",
    brand: "Local",
    stock: 180,
    image: "https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/054e83b5ebe789cf4b7b146319df4cfc",
    rating: 4.0,
    reviews: 40,
    discount: 0
  },
  {
    productId: "P007",
    productName: "Chocolate Cake",
    category: "Bakery",
    description: "Delicious chocolate cake",
    price: 350,
    unit: "500g",
    brand: "BakeHouse",
    stock: 20,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTs9mSB7H8v9txvmBq8WtQtbmUDhIfmwe0SdCWKZDehdCU53oHwq6fjYcfAFcKwUrUl7z8MtNNUk13NxjBPQ5_w-eBtZPlIZw6MgkwNNWKB",
    rating: 4.8,
    reviews: 90,
    discount: 20
  },
  {
    productId: "P008",
    productName: "Bread",
    category: "Bakery",
    description: "Fresh white bread",
    price: 40,
    unit: "400g",
    brand: "Britannia",
    stock: 70,
    image: "bread.jpg",
    rating: 4.3,
    reviews: 75,
    discount: 5
  },
  {
    productId: "P009",
    productName: "Coca Cola",
    category: "Beverages",
    description: "Soft drink",
    price: 40,
    unit: "750ml",
    brand: "Coca Cola",
    stock: 120,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY3SGE1vQHtrOjyJvVhfQtwvtJBl4ZlK6wi66kDQok42A1RaL2KO1wzpQ5rX1wHcAIe05R9H0izAT52_TG_YMk-FiNmJk5creqT5GnJYA&s=10",
    rating: 4.5,
    reviews: 140,
    discount: 10
  },
  {
    productId: "P010",
    productName: "Orange Juice",
    category: "Beverages",
    description: "Fresh juice",
    price: 120,
    unit: "1L",
    brand: "Real",
    stock: 60,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcStEcj7P9WVwHQenNNb1UIOcn36Xm3mn20pPVwHf7ycnmBBS1G-aLOcFF5McRtR1VqDLDw_Kfa21hcNhxNvzMN6giZ_nFPKPcjo_mL-Zb44dfD2VvLXsknnoA&usqp=CAc",
    rating: 4.4,
    reviews: 100,
    discount: 5
  },
  {
    productId: "P011",
    productName: "Lays Chips",
    category: "Snacks",
    description: "Crispy chips",
    price: 20,
    unit: "50g",
    brand: "Lays",
    stock: 200,
    image: "chips.jpg",
    rating: 4.2,
    reviews: 150,
    discount: 0
  },
  {
    productId: "P012",
    productName: "Biscuits",
    category: "Snacks",
    description: "Cream biscuits",
    price: 30,
    unit: "100g",
    brand: "Oreo",
    stock: 90,
    image: "https://m.media-amazon.com/images/I/71CVgabuKtL._SX679_.jpg",
    rating: 4.6,
    reviews: 130,
    discount: 5
  },
  {
    productId: "P013",
    productName: "Basmati Rice",
    category: "Grains",
    description: "Premium rice",
    price: 500,
    unit: "5kg",
    brand: "India Gate",
    stock: 40,
    image: "https://rukminim2.flixcart.com/image/1536/1536/xif0q/rice/d/o/i/-original-imah8xxmbs7ffc8y.jpeg?q=90",
    rating: 4.7,
    reviews: 110,
    discount: 20
  },
  {
    productId: "P014",
    productName: "Wheat Flour",
    category: "Grains",
    description: "Whole wheat atta",
    price: 250,
    unit: "5kg",
    brand: "Aashirvaad",
    stock: 60,
    image: "https://m.media-amazon.com/images/I/71T2C4NmdTL._SX569_.jpg",
    rating: 4.5,
    reviews: 95,
    discount: 10
  },
  {
    productId: "P015",
    productName: "Frozen Peas",
    category: "Frozen",
    description: "Green peas",
    price: 120,
    unit: "500g",
    brand: "Safal",
    stock: 30,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ5el9zuil1MA-oyynQJZi1U634u_uNIR4KUTBNYRfP3ieeQ8qZ4aXJUJ9WVwmfMOwx-cY_RAYQ1lWHdsI4WU9mIpli3y53",
    rating: 4.3,
    reviews: 45,
    discount: 5
  },
  {
    productId: "P016",
    productName: "Ice Cream",
    category: "Frozen",
    description: "Vanilla ice cream",
    price: 200,
    unit: "1L",
    brand: "Kwality Walls",
    stock: 25,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRQ8c4JQH8s-CB8BzwgWQxP42cm7TQ_2YT53JXqYUAa3aayJnkUdcAsNoTCZItgq2-o9P6tiElhcndaH6lHvLrJoYpTBJpDYg",
    rating: 4.8,
    reviews: 150,
    discount: 15
  },
  {
    productId: "P017",
    productName: "Shampoo",
    category: "Personal Care",
    description: "Hair shampoo",
    price: 180,
    unit: "500ml",
    brand: "Clinic Plus",
    stock: 70,
    image: "https://m.media-amazon.com/images/I/31zSEkxHgXL._SY300_SX300_QL70_FMwebp_.jpg",
    rating: 4.2,
    reviews: 60,
    discount: 10
  },
  {
    productId: "P018",
    productName: "Soap",
    category: "Personal Care",
    description: "Bath soap",
    price: 40,
    unit: "100g",
    brand: "Lux",
    stock: 100,
    image: "https://m.media-amazon.com/images/I/51Bge9Szy2L._SY450_.jpg",
    rating: 4.1,
    reviews: 55,
    discount: 0
  },
  {
    productId: "P019",
    productName: "Detergent Powder",
    category: "Household",
    description: "Clothes washing powder",
    price: 220,
    unit: "1kg",
    brand: "Surf Excel",
    stock: 80,
    image: "https://m.media-amazon.com/images/I/71hSVcOSZUL._SY450_.jpg",
    rating: 4.6,
    reviews: 130,
    discount: 10
  },
  {
    productId: "P020",
    productName: "Dish Wash Liquid",
    category: "Household",
    description: "Dish cleaning liquid",
    price: 150,
    unit: "500ml",
    brand: "Vim",
    stock: 60,
    image: "https://m.media-amazon.com/images/I/51rVxbMt0OL._SY300_SX300_QL70_FMwebp_.jpg",
    rating: 4.4,
    reviews: 90,
    discount: 5
  }
];

module.exports = products;